### ISSUE TITLE
Добавить полнотекстовый поиск для версии API v1.3

### ISSUE THREAD

**Issue by dwkdr** [mdwitr0/kinopoiskdev#116]
**Описание функции**
Обновление полнотекстового поиска с версии 1.2 до 1.3

**Пояснение**
Больше единообразия в JSON ответах, следовательно, меньше кода и более простая поддержка оного

**Comment by mdwitr0** [comment]
Это сделано специально для оптимизации поиска.
Полнотекстовый поиск использует другую базу данных, все данные которые возвращаются в ответе учитываются в качестве аргументов поиска

**Comment by mdwitr0** [comment]
Добавлю в v1.4 одинаковые модели  респонса для полнотекстового поиска и поиска по фильтрам
