### ISSUE TITLE
Данные пользователя

### ISSUE THREAD

**Issue by and7ey** [mdwitr0/kinopoiskdev#132]
Нужна возможность извлекать данные по конкретному пользователю (возможно, после авторизации) - например, выставленные оценки или список Буду смотреть.

**Comment by mdwitr0** [comment]
Привет, спасибо за Issue. Это для каких задач будет использоваться? 
Подобный функционал планируется, но не публичный, а в рамках миграции данных в openmoviedb

**Comment by and7ey** [comment]
Мне нужно для следующих задач - 
1) перенести оценки из кинопоиска куда-нибудь во вне (желательно, сохранив дату оценки)
2) переносить оценки из одного аккаунта кинопоиска в другой (так исторически сложилось, что все оценки в одном аккаунте, а подписка на другом - новые оценки ставят именно в другом аккаунте)
3) аналогично надо синхронизировать списки "буду смотреть" между двумя аккаунтами
4) еще нужно синхронизация списка "буду смотреть" со сторонними сервисами - чтобы, например, автоматически получать уведомления о появлении фильмов из списка "буду смотреть" на трекерах (к сожалению, на кинопоиске теперь ничего почти нет и не появляется)

**Comment by and7ey** [comment]
"Буду смотреть", похоже, доступны без авторизации. Например, https://www.kinopoisk.ru/user/1960323/movies/

**Comment by mdwitr0** [comment]
Изучил требования и возможности
Могу сделать ручку, которая вернет:
1. Оценки к фильмам
2. Фильмы в списке "буду смотреть"
3. Рецензии


Остальное я не смогу реализовать на стороне api, для надежности и большего контроля это стоит делать в каком-то расширении для браузера или приложении. Я не хочу брать на себя хранение логинов и паролей, а так же гарантировать стабильность работы в кинопоиске в режиме реального времени)

Работа с ним - всегда приключения)

На следующей неделе я подумаю над реализацией, и возьму в работу

**Comment by mdwitr0** [comment]
Я попробовал реализовать, все получилось, но пока не получилось сделать этот функционал стабильным. 
Я буду тестировать и искать способы, но пока что вижу это так:
При получении запроса, я буду получать данные от кинопоиска, обрабатывать их и отдавать в ответ. 
Но тут могут быть проблемы со стабильностью, я пока что их не смог решить

Собирать на фоне не получается, так как id пользователей я могу получить только из отзывов, но там всего 30тыс уникальных id, это явно не все возможны пользователи)

**Comment by and7ey** [comment]
Наверное, можно получать запрос от пользователя, возвращать ему статус "Принято", в фоне скачивать данные, кэшировать их (пользователь в это время будет получать статус "В обработке"), а когда все будет готово - на запрос статуса возвращать данные.

**Comment by mdwitr0** [comment]
Я примерно так и думал, вероятно это единственный хороший вариант тут. Спасибо!

**Comment by mdwitr0** [comment]
Я до сентября в отпуске, к сентябрю соберу новые фичи к релизу, и в него добавлю этот функционал после отпуска

**Comment by mdwitr0** [comment]
@and7ey привет, пока что сталкиваюсь с большим количеством проблем по этому кейсу. Там уних достаточно костыльно все сделано, у разных пользователей могут быть разные интерфейсы, разные типы данных и списки.  Сейчас рассматриваю другие способы получения данных

**Comment by mdwitr0** [comment]
В общем пока нет временных ресурсов на данную задачу, закрою ее пока что
