### ISSUE TITLE
Добавить в метод Search параметр isSeries

### ISSUE THREAD

**Issue by lengvizd** [mdwitr0/kinopoiskdev#133]
Предлагаю добавить в метод Search параметр isSeries.

Метод Search прекрасно справляется с пользовательскими запросами, учитывая ошибки, опечатки, варианты и т.д. Это делает метод очень удобным. При этом он дает минимально необходимую репрезентацию элемента, которая позволяет собственно элемент идентифицировать.

Однако идентификация представляется неполной, если нет понимания, является ли элемент фильмом или сериалом (из-за особенностей типизации в самой базе данных КП из поля type этого не следует). Поэтому представляется, что этот параметр будет удобным дополнением к существующим.

Честно признаюсь, это было бы мегаудобно для моего проекта, т.к. сократило бы количество обращений к КП (и расход лимита), но реквест сделал, т.к. предполагаю что не только мне такая фича пригодится.

**Comment by lengvizd** [comment]
Хм, написал реквест и в итоге нашел способ как не обращаясь лишний раз к КП узнать, сериал или фильм.

Параметр movieLength дает значение 0, если это сериал, и количество минут, если это фильм.

Если кому понадобится в будущем

**Comment by mdwitr0** [comment]
Привет, я добавлю это поле, в следующем релизе)
