### ISSUE TITLE
Выкидывает SyntaxError когда нету интернета

### ISSUE THREAD

**Issue by ovgamesdev** [mdwitr0/kinopoiskdev#134]
PS: только что заметил что не там написал: https://github.com/OpenMovieDB/kinopoiskdev_client

**Опишите проблему**
Выкидывает ошибку `[SyntaxError: JSON Parse error: Unexpected token: N]` когда нету интернета

**Шаги для воспроизведения проблемы**
Отключить интернет, 
```js
const res = await api.kp.movie.getBySearchQuery(queryKP)
```

**Ожидаемое поведение**
Из `res: { error, message }` получить ошибку и сообщение

**Фактическое поведение**
Выкидывает ошибку приходится отлавливать через `try catch`

**Дополнительная информация**
В других методах такая-же ошибка (я проверял только `getById` и `getBySearchQuery`)

**Comment by mdwitr0** [comment]
Да, и правда не туда))
После отпуска поправлю, спасибо)
