### ISSUE TITLE
Добавить параметр includeGenres в запрос

### ISSUE THREAD

**Issue by Gromov812** [mdwitr0/kinopoiskdev#135]
**Описание функции**
Добавить параметр поиска под условным названием "includeGenres", который фильтровал бы выдачу по жанрам с логиком И (сейчас ИЛИ).

**Пояснение**
Гораздо более точный поиск по жанрам. Комедийный мультфильм или комедийный боевик можно будет получать без фильтрации большого массива на фронте.

**Comment by mdwitr0** [comment]
Как тебе было бы удобно передавать такие жанры?
Сейчас есть спец символ ! - который исключает определенные жанры
["!Боевик",  "Детский"]
как вариант сделать новый query параметр genres.name.and=
ну либо как-то так сделать ["+Боевик",  "+Детский"]

**Comment by Gromov812** [comment]
> Как тебе было бы удобно передавать такие жанры? Сейчас есть спец символ ! - который исключает определенные жанры ["!Боевик", "Детский"] как вариант сделать новый query параметр genres.name.and= или как ты предложил includeGenres ну либо как-то так сделать ["+Боевик", "+Детский"]

Ох, извини, поздно увидел! Было бы удобнее одним из описанных выше способов! :)

**Comment by Gromov812** [comment]
Ещё было бы просто замечательно, если бы был параметр отдающий "Похожие фильмы". Но, полагаю, этой инфы попросту нет в БД. Я прав?
![Снимок экрана в 2023-09-04 12-23-37](https://github.com/mdwitr0/kinopoiskdev/assets/105276303/af6dec15-8b3c-4a36-ac21-be87a0e18eed)

**Comment by mdwitr0** [comment]
> Ещё было бы просто замечательно, если бы был параметр отдающий "Похожие фильмы" массивом айдишников. Но, полагаю, этой инфы попросту нет в БД. Я прав? ![Снимок экрана в 2023-09-04 12-23-37](https://user-images.githubusercontent.com/105276303/265416011-af6dec15-8b3c-4a36-ac21-be87a0e18eed.png)

Они хранятся в поле similarMovies у каждого фильма)

**Comment by mdwitr0** [comment]
После залива в main, можно будет использовать такую конструкцию ["+Боевик", "+Детский"] и в жанрах и в странах
