### ISSUE TITLE
Флаг hasMore и  

### ISSUE THREAD

**Issue by qoiqvi** [mdwitr0/kinopoiskdev#141]
**Описание функции**
1. Мне кажется было бы удобнее, если бы флаг hasMore приходил с бэка, понятно что на фронте это делается одной строчкой, просто мне кажется это улучшит dx)
2.  Хотелось бы что бы в similarMovies приходил и рейтинг фильма

**Comment by mdwitr0** [comment]
В чем задача hasMore?

**Comment by roxxel** [comment]
> В чем задача hasMore?

Скорее всего имеется ввиду для поиска - `hasMorePages`

**Comment by mdwitr0** [comment]
Думаю, что такое нет смысла пока что добавлять)
