### ISSUE TITLE
У эпизода нет даты

### ISSUE THREAD

**Issue by luzmane** [mdwitr0/kinopoiskdev#151]
**Опишите проблему**
У эпизода нет даты, несмотря на документацию

**Шаги для воспроизведения проблемы**
Послать запрос на https://api.kinopoisk.dev/v1/season?page=1&limit=10&movieId=77044

**Ожидаемое поведение**
У объекта эпизод есть и заполняется поле date

**Фактическое поведение**
поле отсутствует

![image](https://github.com/mdwitr0/kinopoiskdev/assets/11422326/228bd198-d6e7-4ade-ba6b-8edea8467006)

![image](https://github.com/mdwitr0/kinopoiskdev/assets/11422326/c4f3fefd-1be3-4b5d-8078-7c178e16dcb6)

**Comment by mdwitr0** [comment]
в этом issue исправлено https://github.com/mdwitr0/kinopoiskdev/issues/139
добавится с новым релизом поле airDate
