### ISSUE TITLE
API v.1.4. Результат поиска включает все возможные фильмы

### ISSUE THREAD

**Issue by luzmane** [mdwitr0/kinopoiskdev#166]
**Опишите проблему**
Используя новую версию API, результат поиска включает все возможные фильмы, в отличии от предыдущей версии, да и от ожидаемого поведения.

**Шаги для воспроизведения проблемы**
Я попробовал оба варианта поиска с одинаковым результатом. Задача - найти фильм по имени и году выпуска. Ищу фильм "Гарри Поттер и философский камень" 2001 года с КП id = 689. "На руках" имя фильма и год.
***Первая попытка:***
* Послать запрос: 
https://api.kinopoisk.dev/v1.4/movie?limit=50&selectFields=alternativeName&selectFields=backdrop&selectFields=countries&selectFields=description&selectFields=enName&selectFields=externalId&selectFields=facts&selectFields=genres&selectFields=id&selectFields=logo&selectFields=movieLength&selectFields=name&selectFields=persons&selectFields=poster&selectFields=premiere&selectFields=rating&selectFields=ratingMpaa&selectFields=releaseYears&selectFields=seasonsInfo&selectFields=sequelsAndPrequels&selectFields=slogan&selectFields=top250&selectFields=videos&selectFields=year&name=Гарри Поттер и философский камень&year=2001
* Ожидаемое поведение - найден только один фильм с Id 689
* Фактическое поведение - найдено много фильмов

***Вторая попытка (использовал swagger API):***
* Ввести "name=Гарри Поттер и философский камень&year=2001"
* В результате послан запрос:
https://api.kinopoisk.dev/v1.4/movie/search?page=1&limit=10&query=name%3D%D0%93%D0%B0%D1%80%D1%80%D0%B8%20%D0%9F%D0%BE%D1%82%D1%82%D0%B5%D1%80%20%D0%B8%20%D1%84%D0%B8%D0%BB%D0%BE%D1%81%D0%BE%D1%84%D1%81%D0%BA%D0%B8%D0%B9%20%D0%BA%D0%B0%D0%BC%D0%B5%D0%BD%D1%8C%26year%3D2001
* Ожидаемое поведение - найден только один фильм с Id 689
* Фактическое поведение - найдено много фильмов

**Comment by mdwitr0** [comment]
Привет, в поиске с фильтрам в v1.4 нет поиска по названию, оно в search, твой запрос будет выглядеть так search?query=Гарри Поттер и философский камень 2001

**Comment by luzmane** [comment]
Я использовал `search?query` во вторых попытках: 
* `https://api.kinopoisk.dev/v1.4/movie/search?page=1&limit=10&query=name=Гарри Поттер и философский камень&year=2001`
* `https://api.kinopoisk.dev/v1.4/movie/search?page=1&limit=10&query=name=Гарри Поттер и философский камень,year=2001`
(разница между верхними запросами в `&` перед year)
С тем же результатом - много фильмов.

Если я тебя правильно понимаю, в query надо кидать всё в кучу (без уточнение что за поле) - поиск разберётся?

**Comment by mdwitr0** [comment]
> Я использовал `search?query` во вторых попытках:
> 
> * `https://api.kinopoisk.dev/v1.4/movie/search?page=1&limit=10&query=name=Гарри Поттер и философский камень&year=2001`
> * `https://api.kinopoisk.dev/v1.4/movie/search?page=1&limit=10&query=name=Гарри Поттер и философский камень,year=2001`
>   (разница между верхними запросами в `&` перед year)
>   С тем же результатом - много фильмов.
> 
> Если я тебя правильно понимаю, в query надо кидать всё в кучу (без уточнение что за поле) - поиск разберётся?

Это полнотекстовый поиск, пользоваться им нужно так, как ты будучи пользователем искал нужный фильм
query это твой человекопонятный запрос.
То есть когда ты ищешь что-то в яндексе ты пишешь просто название фильма, или добавляешь еще и год. Тут так же ты просто пишешь название фильма на любом языке и если нужно уточнить год, указываешь его в этой же строке

Все что находится в query он воспринимает буквально, и будет искать эти слова в фильмах

**Comment by luzmane** [comment]
Спасибо 😃
