### ISSUE TITLE
Расхождение типов в спецификации MovieDtoV1_4 и ответе в методе /v1.4/movie/{id}

### ISSUE THREAD

**Issue by Niro** [mdwitr0/kinopoiskdev#167]
**Опишите проблему**
Поле networks объявлено как array, а в ответе на /v1.4/movie/{id} возвращается объект.

**Шаги для воспроизведения проблемы**
Вызвать `https://api.kinopoisk.dev/v1.4/movie/1044279`

**Ожидаемое поведение**
Поле networks в ответе на вызов /v1.4/movie/1044279 является массивом объектов 

**Фактическое поведение**
Поле networks является объектом

**Дополнительная информация**
Из спецификации
```yaml
networks:
  nullable: true
  type: array
  items:
    $ref: '#/components/schemas/NetworksV1_4'
```

Отредактированный ответ
```json
{
  <...>
  "networks": {
    "items": [
      {
        "name": "Netflix"
      }
    ]
  },
  <...>
}
```

**Comment by mdwitr0** [comment]
Поправил, проблема была в контракте

**Comment by Niro** [comment]
@mdwitr0 Все еще возвращается как объект.
```json
  "networks": {
    "items": [
      {
        "name": "Netflix"
      }
    ]
  },
```

**Comment by mdwitr0** [comment]
Он и должен быть объектом

**Comment by Niro** [comment]
Да, увидел, что в спеке обновилось. Когда вчера смотрел все еще было как type: array
