### ISSUE TITLE
Swagger doc is partial

### ISSUE THREAD

**Issue by luzmane** [mdwitr0/kinopoiskdev#32]
**Опишите проблему**
Swagger doc provide only part of the scheme

**Ожидаемое поведение**
Full scheme of a response

**Дополнительная информация**
Example:
* missing: ```Movie.productionCompanies``` in the scheme, but received in response
* ```Movie.year``` incorrect example: "1860-2030"
* season section - on part of the fields one can guess only by search request params

**Comment by mdwitr0** [comment]
@luzmane productionCompanies is deprecated property. I stopped parse our the information on it.
Is this important property for you?

**Comment by luzmane** [comment]
I fill this property of movie metadata in Emby, but I didn't find where I present it. So it's more "nice to have", but not mandatory
