### ISSUE TITLE
Поиск фильма\сериала по полю seasonsInfo

### ISSUE THREAD

**Issue by luzmane** [mdwitr0/kinopoiskdev#65]
Как искать фильм\сериал, если полу - массив?
Например, как найти фильм, у которого seasonsInfo не пустой?
`https://api.kinopoisk.dev/v1/movie?seasonsInfo=!null` возвращает с `"seasonsInfo": []`,
`https://api.kinopoisk.dev/v1/movie?seasonsInfo.episodesCount!=0` тоже

**Comment by mdwitr0** [comment]
Например можно так получить все записи у которых есть от 1 до 10 сезонов
`https://api.kinopoisk.dev/v1/movie?selectFields=seasonsInfo&page=1&limit=10&seasonsInfo.number=1-10`

Так вернет все сериалы где от 20 до 100 эпизодов в сезоне
 `https://api.kinopoisk.dev/v1/movie?selectFields=seasonsInfo&page=1&limit=10&seasonsInfo.episodesCount=20-100`
 
 !null не для всех полей работает, а только для определенных
