### ISSUE TITLE
Поиск по нескольким ID

### ISSUE THREAD

**Issue by luzmane** [mdwitr0/kinopoiskdev#70]
**Описание функции**
Поддержка поиска фильмов и сериалов по нескольким id в виде: `https://api.kinopoisk.dev/v1/movie?id=689,688`, сейчас возвращается только один фильм

**Пояснение**
При получении sequelsAndPrequels мне не хватает некоторых полей (externalId), но перегружать sequelsAndPrequels результат кучей всяких дополнительных данных нет смысла - не всем это надо. А использую поиск по нескольким ID я могу собрать ID из sequelsAndPrequels и получить необходимое поле

**Метки (необязательно)**
api

**Comment by mdwitr0** [comment]
Все верно, так как перечислять нужно так `id=689&id=688` или так `id[]=689&id[]=688`, в сваггере же корректно все формируется.

**Comment by mdwitr0** [comment]
В sequelsAndPrequels я могу добавить поля чуть позже, но именно что добавить, я не могу делать скрытые поля во вложенных объектах так как это приведет к неразберихе. Сейчас все поля что существуют - они доступны в модели и в ответах. Исключение пагинация, там нужно выбирать самому какие поля получать

**Comment by luzmane** [comment]
sequelsAndPrequels - добавлять ничего не надо - необходимый минимум есть.
`id=689&id=688` - сработал, так что закрываю feature request
